name: release

# TODO: trigger this workflow when renovate merged a ameba-color-palette.css PR
on:
  push:
    branch:
      - main
  schedule:
    # NOTE: at 7:05 am every day, JST
    - cron: '5 22 * * *'
  workflow_dispatch:

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - run: npm install -g npm@"$(jq -r .engines.npm package.json)"
      - run: git config --global user.name 'github-actions[bot]'
      - run: git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - run: npm ci
      - run: git worktree add ./release release
      - run: >
          npm --json --silent info ameba-color-palette.css versions
          | jq -r '.[]'
          | xargs -n 1 ./index.sh
      - run: git show --format=fuller
        working-directory: release
      - name: push release branch
        run: |
          set -x
          if [[ "$GITHUB_EVENT_NAME" =~ ^(push|pull_request)$ ]]
          then
            git push --dry-run origin release
          else
            git push origin release
          fi
        working-directory: release
      - name: push tags
        run: |
          set -x
          if [[ "$GITHUB_EVENT_NAME" =~ ^(push|pull_request)$ ]]
          then
            git push --dry-run --tags origin
          else
            git push --tags origin
          fi
        working-directory: release
      - run: git worktree remove ./release
