name: release

on:
  push:
  pull_request:
  schedule:
    # NOTE: at 7:05 am every day, JST
    - cron: '5 22 * * *'
  workflow_dispatch:

jobs:
  release:
    name: release
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: git config --global user.name 'github-actions[bot]'
      - run: git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - run: npm ci
      - run: git worktree add ./release release
      - run: >
          npm --json --silent info ameba-color-palette.css versions |
          jq -r '.[]' |
          xargs -n 1 ./index.sh
      - run: git show --format=fuller
        working-directory: release
      - run: |
          set -x
          if [[ "$GITHUB_EVENT_NAME" =~ ^(push|pull_request)$ ]]
          then
            git push --dry-run origin release
          else
            git push origin release
          fi
        working-directory: release
        name: push release branch
      - run: |
          set -x
          if [[ "$GITHUB_EVENT_NAME" =~ ^(push|pull_request)$ ]]
          then
            git push --dry-run --tags origin
          else
            git push --tags origin
          fi
        working-directory: release
        name: push tags
      - run: git worktree remove ./release
