name: test

on:
  - push
  - pull_request

jobs:
  build:
    name: build
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm install -D ameba-color-palette.css
      - run: node index.js
