name: test

on:
  - push
  - pull_request

jobs:
  build:
    name: build
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm
      - uses: openameba/action-npm-cache/restore@v1
      - run: npm install -g npm@"$(jq -r .engines.npm package.json)"
      - run: npm ci
      - run: node index.js
      - if: github.ref_name == 'main'
        uses: openameba/action-npm-cache/save@v1
